package org.grizz.model.enummerations;

public enum BuildingType {

    METAL_MINE,
    CRYSTAL_MINE,
    EXTRACTOR_DEUTERIUM,
    SOLAR_POWER,
    FUSION_REACTOR,
    ROBOTICS_FACTORY,
    NANITE_FACTORY,
    SHIPYARD,
    MAGAZINE_METALS,
    CRYSTAL_STORAGE,
    THE_TANK_OF_A_DEUTERIUM,
    RESEARCH_LABORATORY,
    TERRAFORMER,
    DEPOSIT_ALLIANCE,
    MISSILE_SILO
}
